// This gets injected into the Leaflet app autogenerated by QGIS2web

var hortis = {};

hortis.plethLevels = {
    0: "#f7fcfd",
    5: "#e5f5f9",
    10: "#ccece6",
    20: "#99d8c9",
    50: "#66c2a4",
    100: "#41ae76",
    200: "#238b45",
    500: "#005824"
};

hortis.revKeys = Object.keys(hortis.plethLevels).reverse().map(function (stringKey) {
    return Number(stringKey)
});

hortis.getColor = function (count) {
    for (var i = 0; i < hortis.revKeys.length; ++ i) {
        var key = hortis.revKeys[i];
        if (count > key) {
            return hortis.plethLevels[key];
        }
    }
};

hortis.plethStyle = function (feature) {
    return {
        fillColor: hortis.getColor(feature.properties.speciesCount),
        weight: 1,
        opacity: 1,
        color: "black",
        //dashArray: '3',
        fillOpacity: 0.7
    };

}